# Generated by Django 5.0 on 2024-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwasteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_joining',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
