# Generated by Django 5.0 on 2024-02-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwasteapp', '0002_remove_profile_date_of_joining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('userr', models.CharField(max_length=100)),
            ],
        ),
    ]
