# Generated by Django 5.0 on 2024-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwasteapp', '0004_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='ruser',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
