# Generated by Django 5.0.2 on 2024-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwasteapp', '0005_completed_ruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='source',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
